create database automated_manager;

drop table passport;
drop table credit_contract;
drop table credit_statement;
drop table employment;
drop table address;
drop table client;

create table client
(
    id               int generated by default as identity primary key,
    first_name       varchar(50)            not null,
    second_name      varchar(50)            not null,
    third_name       varchar(50)            not null,
    family_status    bool                   not null,
    telephone_number varchar(10)            not null unique,
    unique (first_name, second_name, third_name)
);

create table passport
(
    client_id int references client primary key,
    series    int not null,
    number    int not null,
    unique (series, number)
);

create table address
(
    client_id    int references client primary key,
    country_name varchar(50) not null,
    city_name    varchar(50) not null,
    street_name  varchar(50) not null,
    house_number varchar(10) not null
);

create table employment
(
    client_id         int references client primary key,
    start_work        date         not null,
    end_work          date         not null,
    job_title         varchar(100) not null,
    organization_name varchar(50)  not null
);

create table credit_statement
(
    id        int generated by default as identity primary key,
    client_id int references client not null,
    status    bool
);

create table credit_contract
(
    id              int generated by default as identity primary key,
    client_id       int references client not null,
    amount_money    int                   not null,
    amount_days     int                   not null,
    date_of_signing date,
    status          bool
);