create database automated_manager;

create table client
(
    id               int generated by default as identity primary key,
    first_name       varchar(50)            not null,
    second_name      varchar(50)            not null,
    third_name       varchar(50)            not null,
    family_status    bool                   not null,
    telephone_number varchar(10)            not null unique,
    address_id       int references address not null,
    employment_id    int references employment
);

create table passport
(
    id     int references client primary key,
    series int not null,
    number int not null,
    unique (series, number)
);

create table address
(
    id           int generated by default as identity primary key,
    country_name varchar(50) not null,
    city_name    varchar(50) not null,
    street_name  varchar(50) not null,
    house_number varchar(10) not null,
    unique (country_name, city_name, street_name, house_number)
);

create table employment
(
    id                int generated by default as identity primary key,
    start_work        date         not null,
    end_work          date         not null,
    job_title         varchar(100) not null,
    organization_name varchar(50)  not null
);

create table credit_statement
(
    id        int generated by default as identity primary key,
    client_id int references client not null,
    status    bool
);

create table credit_contract
(
    id              int generated by default as identity primary key,
    client_id       int references client not null,
    amount_money    int                   not null,
    amount_days     int                   not null,
    date_of_signing date,
    status          bool
);